### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Matsv** [Matsv/PAaaS#4]
- [ ] Create menu options to quickly go to sections
- [ ] Add the possibility to collapse sections
- [ ] Improve the metadata render speed / comparison display
- [ ] Implement the possibility the collapse sections
- [ ] Improve the whole JavaScript code
- [ ] Add more info? (Sound changes, etc..)
- [ ] List all snapshots (#3)
- [ ] Improve the modules to not break when you change something (Instead regenerate)

More ideas / suggestions?
Let us know :)

**Comment by Pokechu22** [comment]
How about including the default values in the metadata generator?  I think it's feasible to do that since the client _does_ specify them (in the method MCP calls it `entityInit`).

**Comment by Matsv** [comment]
@Pokechu22 great suggestion, will definitely look into that :)
